baseURL = "https://spiffy-TOS.github.io/TheInfiniteJourney/"
languageCode = "en-us"
title = "The Infinite Blog"
theme = "PaperMod"
paginate = 10
publishDir = "docs"
contentDir = "site/content"
layoutDir  = "site/layouts"
staticDir  = "site/static"

[params]
  author = "Spiff"
  description = "Chronicles from the edge of code, chaos, and the cosmos."
  defaultTheme = "dark"
  disableThemeToggle = true
  ShowReadingTime = true
  ShowShareButtons = false
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = false
  mainSections = ["posts"]

  [params.assets]
    css = ["custom.css"]

  [params.homeInfoParams]
    title = "The Infinite Blog"
    content = "Observations, devlogs, and transmissions from beyond the stars."

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Ko-fi"
    url = "https://ko-fi.com/spiffyproductions"
    weight = 3

[markup]
  [markup.highlight]
    noClasses = false

